name: CI
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - uses: Swatinem/rust-cache@v2
      - name: Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Check Rust
        run: cargo fmt --check && cargo clippy -- -Dwarnings
      - name: Test Rust
        run: cargo test
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build with Next.js
        run: yarn build
